# Generated by Django 4.2.1 on 2023-05-24 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
